name: Build iDSK

on:
  push:
    branches: [ main, master ]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # =========================================================
      # 1️⃣  Checkout del repositorio
      # =========================================================
      - name: Checkout repository
        uses: actions/checkout@v4

      # =========================================================
      # 2️⃣  Instalar dependencias básicas
      # =========================================================
      - name: Install dependencies
        run: |
          brew update
          brew install cmake ninja
          brew tap messense/macos-cross-toolchains
          brew install x86_64-unknown-linux-gnu aarch64-unknown-linux-gnu

      # =========================================================
      # 3️⃣  Dar permisos al script de build
      # =========================================================
      - name: Make build script executable
        run: chmod +x ./build_all.sh

      # =========================================================
      # 4️⃣  Ejecutar el script de build
      # =========================================================
      - name: Run build script
        run: ./build_all.sh

      # =========================================================
      # 5️⃣  Subir artefactos generados
      # =========================================================
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iDSK-binaries
          path: dist/*.tar.gz
          if-no-files-found: error