name: Build iDSK

on:
  push:
    branches: [ main, master ]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1️⃣ Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Instalar dependencias
      - name: Install dependencies
        run: |
          brew update
          brew install cmake ninja
          brew tap messense/macos-cross-toolchains
          brew install x86_64-unknown-linux-gnu aarch64-unknown-linux-gnu

      # 3️⃣ Dar permisos al script
      - name: Make build script executable
        run: chmod +x ./build_all.sh
        working-directory: ${{ github.workspace }}

      # 4️⃣ Ejecutar el script de build
      - name: Run build script
        run: ./build_all.sh
        working-directory: ${{ github.workspace }}

      # 5️⃣ Subir todos los artefactos automáticamente
      - name: Upload all build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iDSK-artifacts
          path: dist/*.tar.gz
          if-no-files-found: error